org: nayeliguerrero
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  timeout: 20  
  iam:
    role: arn:aws:iam::306083006368:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda

  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/{alumno_id}
          method: put
          cors: true

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/{alumno_id}
          method: delete
          cors: true

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/{alumno_id}
          method: get
          cors: true

